name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
# env:
#   DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
#   DOCKER_PASSWORD: "${{ vars.DOCKER_PASSWORD }}"

jobs:
  build__push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jazibumer/dc_file:latest && echo "$vars.DOCKER_USERNAME"
    - name: Log in to Docker Hub
      run: docker login -u "${{ vars.DOCKER_USERNAME }}" -p "${{ vars.DOCKER_PASSWORD }}"
    - name: push 
      run: docker push jazibumer/dc_file:latest
      
