name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD-test }}" | docker login -u "${{ secrets.DOCKER_USERNAME-test }}" --password-stdin

    - uses: actions/checkout@v4

    - name: Build and Push the Docker image
      run: docker build . --file Dockerfile --tag jazibumer/dc_file:latest && docker push jazibumer/dc_file:latest
