name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_push:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t jazibumer/dc_file:latest .

    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push jazibumer/dc_file:latest
