name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DOCKER_USERNAME: "{{secrets.DOCKER_USERNAME}}"
  DOCKER_PASSWORD: "{{secrets.DOCKER_PASSWORD}}"
jobs:
  build__push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Log in to Docker Hub
      run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - name: push 
      run: docker push jazibumer/dc_file:latest
      
